# Generated by Django 3.2.8 on 2021-10-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=16)),
                ('product_name', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('GBP', 'Pound')], max_length=256)),
            ],
        ),
    ]
